Add basics 1
aichner/Cloud-Homepage pull request #1
Opened 2020-05-14 21:56 UTC by LucaAllmaier

**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [ ] Have you updated or added documentation for the change?
 - [x] Have you tested your changes with successful results?

**Type of Changes:**

 
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**
- currently, the copyright date is only 2019
- currently, the project only consists of the template
- currently, there is no LandingPage 

**What is the new behavior (if this is a feature change)?**
- The copyright dates in all files have been changed to 2019-2020.
- The output of unused components has been removed.
- A LandingPage has been created.

**Other information**:
-

2020-05-14 22:18 UTC, Aichnerc requested changes
Please remove all unused files and comonents.

2020-05-14 22:18 UTC, Aichnerc commented on src/App.js
> -import Routes from "./Routes";
Remove all unused files like Routes.js and all components.

2020-05-15 08:28 UTC, Aichnerc approved these changes
LGTM 👀

2020-05-15 08:32 UTC, schettn requested changes
Should be ok after a adjustment

2020-05-15 08:32 UTC, schettn commented on src/Routes.js
> +
You should remove this newline.

2020-05-15 08:32 UTC, schettn commented on src/components/pages/LandingPage/LandingPage.scss
> +}
Licence missing

2020-05-15 09:11 UTC, LucaAllmaier commented on src/Routes.js
> +
The whole file has been removed in a later commit

2020-05-15 12:05 UTC, kleberbaum approved these changes
Should be ok to merge.

2020-05-15 12:21 UTC, kleberbaum commented
In the PR message this:

> **What is the current behavior? (link to any open issues here)**
> 
>   * currently, the copyright date is only 2019
> 
>   * currently, the project only consists of the template
> 
>   * currently, there is no LandingPage
> 
> 

Should be changed to something like this:

**What is the current behavior? (link to any open issues here)**
   - Currently the copyright covers only 2019.
   - Currently the project only consists of the template.
   - Currently there is no LandingPage.

2020-05-15 12:54 UTC, schettn approved these changes
LGTM

2020-05-15 17:19 UTC, merged